CREATE TABLE IF NOT EXISTS public.locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    url text NOT NULL,
    -- Optional rich details
    address text,
    phone text,
    website text,
    plus_code text,
    rating double precision,
    user_ratings_total integer,
    opening_hours jsonb,
    attributes jsonb,
    place_id text,
    lat double precision,
    lng double precision,

    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),

    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.locations IS 'Club locations that users can choose from, including a human-readable name and a maps URL.';

-- Enable Row Level Security
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

-- Column-level security: restrict access for client roles to only the safe columns
REVOKE ALL ON TABLE public.locations FROM PUBLIC, anon, authenticated;

-- Backend retains full access
GRANT ALL ON TABLE public.locations TO service_role;

-- Allow public/client read access to non-sensitive columns
GRANT SELECT (
  id, name, url,
  address, phone, website, plus_code,
  rating, user_ratings_total, opening_hours, attributes,
  place_id, lat, lng,
  created_at, updated_at
) ON public.locations TO anon, authenticated;
GRANT SELECT ON TABLE public.locations TO anon, authenticated;
GRANT INSERT (
  name, url,
  address, phone, website, plus_code,
  rating, user_ratings_total, opening_hours, attributes,
  place_id, lat, lng
) ON public.locations TO authenticated;
GRANT UPDATE (
  name, url,
  address, phone, website, plus_code,
  rating, user_ratings_total, opening_hours, attributes,
  place_id, lat, lng
) ON public.locations TO authenticated;
GRANT DELETE ON public.locations TO authenticated;

-- Create policies
CREATE POLICY "Public locations are viewable by everyone"
ON public.locations FOR SELECT
TO authenticated, anon
USING (true);

-- Admin-only write policies
CREATE POLICY "Only admins can insert locations"
ON public.locations FOR INSERT
TO authenticated
WITH CHECK ((select public.is_admin()));

CREATE POLICY "Only admins can update locations"
ON public.locations FOR UPDATE
TO authenticated
USING ((select public.is_admin()))
WITH CHECK ((select public.is_admin()));

CREATE POLICY "Only admins can delete locations"
ON public.locations FOR DELETE
TO authenticated
USING ((select public.is_admin()));

-- Trigger to keep updated_at current on row modification (reuses public.set_updated_at)
CREATE TRIGGER set_locations_updated_at
BEFORE UPDATE ON public.locations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

