name: Deploy Migrations

on:
  push:
    branches:
      - main
    paths:
      - "supabase/migrations/**"
      - ".github/workflows/deploy-migrations.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Preview
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Push migrations to Supabase
        run: supabase db push
